#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WL_CMD="${WORKLINE_WL_CMD:-go run ./cmd/wl}"
PROJECT_ID="${WORKLINE_PROJECT_ID:-${WORKLINE_DEFAULT_PROJECT:-}}"

ENV_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file)
      ENV_FILE="${2:-}"
      shift 2
      ;;
    *)
      echo "unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "${PROJECT_ID}" ]]; then
  echo "WORKLINE_PROJECT_ID or WORKLINE_DEFAULT_PROJECT is required" >&2
  exit 1
fi

cd "$ROOT_DIR"

declare -a roles=("planner" "executor" "reviewer")
declare -a actors=("planner-agent" "executor-agent" "reviewer-agent")

env_lines=()

for idx in "${!roles[@]}"; do
  role="${roles[$idx]}"
  actor="${actors[$idx]}"
  ${WL_CMD} rbac bootstrap --project "${PROJECT_ID}" --actor "${actor}" --role "${role}" >/dev/null
  key_json="$(${WL_CMD} api-key create --actor "${actor}" --name "${role}" --json)"
  key_value="$(python -c 'import json,sys; print(json.load(sys.stdin)["key"])' <<<"${key_json}")"
  upper_role="$(echo "${role}" | tr '[:lower:]' '[:upper:]')"
  env_lines+=("WORKLINE_${upper_role}_ACTOR_ID=${actor}")
  env_lines+=("WORKLINE_${upper_role}_API_KEY=${key_value}")
done

if [[ -n "${ENV_FILE}" ]]; then
  {
    echo "# Generated by scripts/bootstrap-automation.sh"
    for line in "${env_lines[@]}"; do
      echo "${line}"
    done
  } > "${ENV_FILE}"
fi

for line in "${env_lines[@]}"; do
  echo "${line}"
done
